/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.org.springframework.boot.spring.boot.starter.data.mongodb)
    implementation(libs.org.springframework.data.spring.data.mongodb)
    implementation(libs.org.springframework.boot.spring.boot.starter.validation)
    implementation(libs.org.springframework.boot.spring.boot.starter.security)
    implementation("org.springframework.boot:spring-boot-starter-web:3.4.2") {
        modules {
            module("org.springframework.boot:spring-boot-starter-tomcat") {
                replacedBy("org.springframework.boot:spring-boot-starter-jetty")
            }
        }
    }
    implementation("org.springframework.boot:spring-boot-starter-jetty:3.4.2")
    implementation(libs.org.springframework.boot.spring.boot.starter.web.services)
    implementation(libs.io.netty.netty.all)
    implementation(libs.joda.time.joda.time)
    implementation(libs.com.github.f4b6a3.uuid.creator)
    implementation(libs.org.reflections.reflections)
    implementation(libs.io.jsonwebtoken.jjwt.api)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.impl)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.gson)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.security.spring.security.test)

    compileOnly("org.projectlombok:lombok:1.18.36")
    annotationProcessor("org.projectlombok:lombok:1.18.36")

    testCompileOnly("org.projectlombok:lombok:1.18.36")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.36")
}

group = "moe.ku6"
version = "0.0.1-SNAPSHOT"
description = "Akamai"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
